services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
    depends_on:
      - mock-users
      - mock-auth

  mock-users:
    build:
      context: ./mock-server
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
      SERVICE_NAME: users-service

  mock-auth:
    build:
      context: ./mock-server
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      PORT: 8082
      SERVICE_NAME: auth-service
